### ISSUE TITLE
rgw/v2: "sync is either slow or stuck" error on primary site of an archive zone env

### ISSUE THREAD

**Issue by mkasturi18** [red-hat-storage/ceph-qe-scripts#399]
On an Archive zone cluster, executing the ceph-qe-scripts from primary site leads to the error "sync is either slow or stuck" which is misleading.

snippet:
2023-02-21 00:37:56,928 INFO: the cluster is multisite
2023-02-21 00:37:56,928 INFO: check sync status
2023-02-21 00:37:56,928 INFO: executing cmd: sudo radosgw-admin sync status
2023-02-21 00:37:57,694 INFO: cmd excuted
2023-02-21 00:37:57,695 INFO:           realm ce96f9b7-8e57-4c8d-ad78-47a63942a693 (ibm-india)
      zonegroup 09e752bb-165b-4e29-ac1f-7414ceca04bb (ibm)
           zone 7f4868db-fd26-4e4c-b000-c762438d9cc5 (blr)
   current time 2023-02-21T00:37:57Z
zonegroup features enabled: resharding
  metadata sync no sync (zone is master)
      data sync source: 54b35f32-9a02-4af9-8af4-b3bbc2072a19
                        not syncing from zone

2023-02-21 00:37:57,695 INFO: No errors or failures in sync status
2023-02-21 00:37:57,695 INFO: check if sync is in progress, if sync is in progress retry 25 times with 60secs of sleep between each retry
2023-02-21 00:37:57,695 ERROR: sync is either slow or stuck
2023-02-21 00:37:57,696 ERROR: Traceback (most recent call last):
  File "/root/kvm/ceph-qe-scripts/rgw/v2/tests/s3_swift/test_bucket_notifications.py", line 271, in <module>
    test_exec(config, ssh_con)
  File "/root/kvm/ceph-qe-scripts/rgw/v2/tests/s3_swift/test_bucket_notifications.py", line 224, in test_exec
    reusable.check_sync_status()
  File "/root/kvm/ceph-qe-scripts/rgw/v2/tests/s3_swift/reusable.py", line 1062, in check_sync_status
    sync_status()
  File "/root/kvm/ceph-qe-scripts/rgw/v2/lib/sync_status.py", line 66, in sync_status
    raise SyncFailedError("sync is either slow or stuck")
v2.lib.exceptions.SyncFailedError: sync is either slow or stuck

**Comment by mkasturi18** [comment]
PR raised for this issue is merged - https://github.com/red-hat-storage/ceph-qe-scripts/pull/400 
closing this issue.
